pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
            dir 'jenkins/'
            label 'MUTILDPL05'
            args '''
                -v /var/lib/package-cache/.npm:/.npm:rw,z
            '''
        }
    }
    environment {
        NODE_ENV = "development"
        GIT_TRUNK_BRANCH = "master"
        S3_BUCKET = "vtx-cloudfront-1"
        S3_REGION_KEY = "us-east-1"
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '100', artifactNumToKeepStr: '20'))
        timestamps()
        timeout(time: 20, unit: 'MINUTES')
        parallelsAlwaysFailFast()
    }
    stages {
        stage('Build') {
            steps {
                //Install NPM components
                sh "npm ci"
                sh "npx cypress install"

                //Run NPM Build
                sh "npm run build:${NODE_ENV}"
            }
        }
        stage('Test') {
            when {
                expression { !env.GIT_BRANCH.equals(env.GIT_TRUNK_BRANCH ) }
            }
            steps {
                sh 'npm run test'
            }
        }
        stage('Lint') {
            when {
                expression { !env.GIT_BRANCH.equals(env.GIT_TRUNK_BRANCH ) }
            }
            steps {
                sh 'npm run lint'
            }
        }
        stage('Cypress') {
            when {
                expression { !env.GIT_BRANCH.equals(env.GIT_TRUNK_BRANCH ) }
            }
            parallel {
                stage('Start local server') {
                    steps {
                        sh returnStatus: true, script: "npm run start:${NODE_ENV}"
                    }
                }
                stage('Run Cypress tests') {
                    steps {
                        sh 'npm run wait'
                        sh 'npm run cypress:run'
                        sh 'npm run cypress:run:e2e'
                        sh 'killall node'
                    }
                }
            }
        }
        stage('Deploy') {
            when {
                expression { env.GIT_BRANCH.equals(env.GIT_TRUNK_BRANCH ) }
            }
            steps {
                script {
                    echo "Current workspace is ${env.WORKSPACE}"
                    
                    //Create the .aws/configuration file to authenticate to S3	
                    withCredentials([usernamePassword(credentialsId: 'cicd-aws-access-key', passwordVariable: 'AWS_SECRET_ACCESS_KEY', usernameVariable: 'AWS_ACCESS_KEY_ID')]) {	
                        sh "aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}"	
                        sh "aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}"	
                        sh "aws configure set default.region ${S3_REGION_KEY}"	
                    }
                    println "env.GIT_COMMIT=${env.GIT_COMMIT}"
                    println "S3_BUCKET=${S3_BUCKET}"
                    sh "export ${NODE_ENV}"
                    sh "printenv NODE_ENV"

                    withCredentials([usernamePassword(credentialsId: 'cicd-platform-ui-imd-credentials', passwordVariable: 'IMD_PASSWORD', usernameVariable: 'IMD_USERNAME')]) {
                        def deployScript = """npm_config_registry=https://binrepo.vtxdev.net/artifactory/api/npm/vtx-ui npx @vertexinc/vtx-ui-tools-deployment deployMicroFrontend --gitCommitSha=${env.GIT_COMMIT} --importMapUsername=${IMD_USERNAME} --importMapPassword=${IMD_PASSWORD} --s3BucketName=${S3_BUCKET}""";
                        def status = sh(returnStatus: true, script: "${deployScript} > deployment_log.txt")
                        def output = readFile('deployment_log.txt').trim()
                        println output
                        println "========== Status Code: ${status} ================"
                        if (status != 0) {
                            println "FAILED. Look above the logs to see the source of the error"
                            currentBuild.result = 'FAILED'
                        }
                    }
                }
            }
        }
    }
    post {
        always {
            echo "Job completed"
        }
    }
}

